### ISSUE TITLE
having trouble rendering google search

### ISSUE THREAD

**Issue by vtomole** [dym/closure#3]
When i type "google search lisp " command I get this
![screenshot from 2016-08-27 20-16-57](https://cloud.githubusercontent.com/assets/8405160/18031024/4e3424c6-6c93-11e6-9cbf-df243aa4c189.png)

**Comment by dym** [comment]
Sorry, but I'm not a maintainer of this package. I just put it on github, because it was only available in cvs (as far as I remember)

**Comment by vtomole** [comment]
Oh okay, I couldn't access the CVS, so it looks like the project has been abandoned. Thanks for putting it on here!

**Comment by dym** [comment]
Yes, project was abandoned long time ago. I just wanted to save it and it's history, because I really liked the idea of the project
